"use client";

import { useState } from "react";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Calculator,
  DollarSign,
  TrendingDown,
  Sparkles,
  Info,
  CheckCircle2,
  ArrowRight,
  Download,
  ExternalLink,
} from "lucide-react";
import { motion } from "framer-motion";

export default function CalculatorPage() {
  const [projectType, setProjectType] = useState("defi");
  const [linesOfCode, setLinesOfCode] = useState("5000");
  const [complexity, setComplexity] = useState("medium");
  const [urgency, setUrgency] = useState("standard");
  const [additionalFeatures, setAdditionalFeatures] = useState<string[]>([]);

  const calculateCost = () => {
    let baseCost = 20000;

    const typeMultipliers: { [key: string]: number } = {
      defi: 1.2,
      nft: 1.0,
      gaming: 1.1,
      infrastructure: 1.3,
      dao: 0.9,
    };
    baseCost *= typeMultipliers[projectType] || 1;

    const loc = parseInt(linesOfCode) || 5000;
    if (loc < 1000) baseCost *= 0.5;
    else if (loc < 3000) baseCost *= 0.7;
    else if (loc < 5000) baseCost *= 0.9;
    else if (loc < 10000) baseCost *= 1.1;
    else baseCost *= 1.4;

    const complexityMultipliers: { [key: string]: number } = {
      low: 0.7,
      medium: 1.0,
      high: 1.4,
      critical: 1.8,
    };
    baseCost *= complexityMultipliers[complexity] || 1;

    const urgencyMultipliers: { [key: string]: number } = {
      standard: 1.0,
      expedited: 1.3,
      emergency: 1.6,
    };
    baseCost *= urgencyMultipliers[urgency] || 1;

    if (additionalFeatures.includes("formal")) baseCost += 8000;
    if (additionalFeatures.includes("bounty")) baseCost += 5000;
    if (additionalFeatures.includes("insurance")) baseCost += 3000;
    if (additionalFeatures.includes("monitoring")) baseCost += 4000;

    return Math.round(baseCost);
  };

  const estimatedCost = calculateCost();
  const subsidyAmount = Math.round(estimatedCost * 0.3);
  const finalCost = estimatedCost - subsidyAmount;

  const toggleFeature = (feature: string) => {
    setAdditionalFeatures((prev) =>
      prev.includes(feature)
        ? prev.filter((f) => f !== feature)
        : [...prev, feature]
    );
  };

  // FIXED: Improved download logic
  const handleDownload = () => {
    const estimateText = `
=========================================
      SOLANA AUDIT COST ESTIMATE
=========================================
Generated by: SecureAuditHub
Date: ${new Date().toLocaleDateString()}
-----------------------------------------

PROJECT DETAILS:
- Type: ${projectType.toUpperCase()}
- Est. Lines of Code: ${linesOfCode}
- Complexity: ${complexity.toUpperCase()}
- Timeline: ${urgency.toUpperCase()}

COST SUMMARY:
- Gross Audit Fee: $${estimatedCost.toLocaleString()}
- Solana Subsidy (30%): -$${subsidyAmount.toLocaleString()}
-----------------------------------------
TOTAL ESTIMATED COST: $${finalCost.toLocaleString()}
-----------------------------------------

ADDITIONAL SERVICES:
${additionalFeatures.length > 0 
    ? additionalFeatures.map(f => `+ ${f.replace(/^\w/, (c) => c.toUpperCase())}`).join('\n') 
    : 'No additional services selected'}

DISCLAIMER:
This is an automated estimate. Final pricing 
is subject to provider review.

Visit us at: https://secureaudithub.com
=========================================
    `.trim();

    const blob = new Blob([estimateText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `audit-estimate-${projectType}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen pt-24 pb-20 px-4">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <Badge className="mb-4 bg-green-100 text-green-700 border-green-200">
            <Calculator className="w-4 h-4 mr-2" />
            Instant Estimate
          </Badge>
          <h1 className="text-5xl font-bold mb-4">
            <span className="bg-gradient-to-r from-green-600 to-purple-600 bg-clip-text text-transparent">
              Audit Cost
            </span>{" "}
            Calculator
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Get an instant estimate of your audit costs with subsidy savings calculated
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <Card className="p-8 border-2">
              <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
                <Sparkles className="w-6 h-6 text-purple-600" />
                Project Details
              </h2>

              <div className="space-y-6">
                <div>
                  <Label className="text-base font-semibold mb-3 block">
                    Project Type
                  </Label>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                    {[
                      { value: "defi", label: "DeFi Protocol", emoji: "💰" },
                      { value: "nft", label: "NFT Platform", emoji: "🎨" },
                      { value: "gaming", label: "Gaming", emoji: "🎮" },
                      { value: "infrastructure", label: "Infrastructure", emoji: "⚙️" },
                      { value: "dao", label: "DAO", emoji: "🏛️" },
                    ].map((type) => (
                      <Button
                        key={type.value}
                        variant={projectType === type.value ? "default" : "outline"}
                        className={`h-auto py-4 ${
                          projectType === type.value
                            ? "bg-gradient-to-r from-purple-600 to-green-600"
                            : ""
                        }`}
                        onClick={() => setProjectType(type.value)}
                      >
                        <div className="text-center">
                          <div className="text-2xl mb-1">{type.emoji}</div>
                          <div className="text-sm">{type.label}</div>
                        </div>
                      </Button>
                    ))}
                  </div>
                </div>

                <div>
                  <Label htmlFor="loc" className="text-base font-semibold mb-3 block">
                    Lines of Code (Approx.)
                  </Label>
                  <Input
                    id="loc"
                    type="number"
                    value={linesOfCode}
                    onChange={(e) => setLinesOfCode(e.target.value)}
                    className="h-12 text-lg"
                    placeholder="5000"
                  />
                  <p className="text-sm text-gray-600 mt-2">
                    Estimate your total smart contract code lines
                  </p>
                </div>

                <div>
                  <Label className="text-base font-semibold mb-3 block">
                    Project Complexity
                  </Label>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    {[
                      { value: "low", label: "Low" },
                      { value: "medium", label: "Medium" },
                      { value: "high", label: "High" },
                      { value: "critical", label: "Critical" },
                    ].map((comp) => (
                      <Button
                        key={comp.value}
                        variant={complexity === comp.value ? "default" : "outline"}
                        className={
                          complexity === comp.value
                            ? "bg-gradient-to-r from-purple-600 to-green-600"
                            : ""
                        }
                        onClick={() => setComplexity(comp.value)}
                      >
                        {comp.label}
                      </Button>
                    ))}
                  </div>
                </div>

                <div>
                  <Label className="text-base font-semibold mb-3 block">
                    Timeline Urgency
                  </Label>
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { value: "standard", label: "Standard", desc: "4-6 weeks" },
                      { value: "expedited", label: "Expedited", desc: "2-3 weeks" },
                      { value: "emergency", label: "Emergency", desc: "< 2 weeks" },
                    ].map((urg) => (
                      <Button
                        key={urg.value}
                        variant={urgency === urg.value ? "default" : "outline"}
                        className={`h-auto py-4 flex-col ${
                          urgency === urg.value
                            ? "bg-gradient-to-r from-purple-600 to-green-600"
                            : ""
                        }`}
                        onClick={() => setUrgency(urg.value)}
                      >
                        <div className="font-semibold">{urg.label}</div>
                        <div className="text-xs opacity-80 mt-1">{urg.desc}</div>
                      </Button>
                    ))}
                  </div>
                </div>

                <div>
                  <Label className="text-base font-semibold mb-3 block">
                    Additional Services (Optional)
                  </Label>
                  <div className="space-y-2">
                    {[
                      { value: "formal", label: "Formal Verification", cost: "+$8k" },
                      { value: "bounty", label: "Bug Bounty Setup", cost: "+$5k" },
                      { value: "insurance", label: "Audit Insurance", cost: "+$3k" },
                      { value: "monitoring", label: "Continuous Monitoring", cost: "+$4k" },
                    ].map((feature) => (
                      <Card
                        key={feature.value}
                        className={`p-4 cursor-pointer transition-all ${
                          additionalFeatures.includes(feature.value)
                            ? "border-2 border-purple-400 bg-purple-50"
                            : "hover:border-purple-200"
                        }`}
                        onClick={() => toggleFeature(feature.value)}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <div
                              className={`w-6 h-6 rounded border-2 flex items-center justify-center ${
                                additionalFeatures.includes(feature.value)
                                  ? "bg-purple-600 border-purple-600"
                                  : "border-gray-300"
                              }`}
                            >
                              {additionalFeatures.includes(feature.value) && (
                                <CheckCircle2 className="w-4 h-4 text-white" />
                              )}
                            </div>
                            <span className="font-medium">{feature.label}</span>
                          </div>
                          <Badge variant="outline">{feature.cost}</Badge>
                        </div>
                      </Card>
                    ))}
                  </div>
                </div>
              </div>
            </Card>
          </div>

          <div className="lg:col-span-1">
            <div className="sticky top-24 space-y-6">
              <Card className="p-6 border-2 border-purple-200">
                <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                  <DollarSign className="w-5 h-5 text-green-600" />
                  Cost Estimate
                </h3>

                <div className="space-y-4">
                  <div className="flex justify-between items-center pb-3 border-b">
                    <span className="text-gray-600">Base Audit Cost</span>
                    <span className="text-xl font-bold">
                      ${estimatedCost.toLocaleString()}
                    </span>
                  </div>

                  <div className="flex justify-between items-center pb-3 border-b">
                    <div className="flex items-center gap-2">
                      <TrendingDown className="w-4 h-4 text-green-600" />
                      <span className="text-green-600 font-medium">Subsidy (30%)</span>
                    </div>
                    <span className="text-xl font-bold text-green-600">
                      -${subsidyAmount.toLocaleString()}
                    </span>
                  </div>

                  <div className="bg-gradient-to-r from-purple-50 to-green-50 p-4 rounded-lg">
                    <div className="flex justify-between items-center">
                      <span className="font-semibold text-gray-700">Your Final Cost</span>
                      <span className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-green-600 bg-clip-text text-transparent">
                        ${finalCost.toLocaleString()}
                      </span>
                    </div>
                  </div>

                  <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                    <div className="flex gap-2 mb-2">
                      <Info className="w-5 h-5 text-blue-600 flex-shrink-0" />
                      <div className="text-sm text-blue-900">
                        <p className="font-semibold mb-1">You Save:</p>
                        <p className="text-2xl font-bold text-blue-600">
                          ${subsidyAmount.toLocaleString()}
                        </p>
                        <p className="text-xs mt-2 text-blue-700">
                          With the Solana Audit Subsidy Program
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-6 space-y-3">
                  {/* UPDATED: Direct open of application source */}
                  <Button 
                    className="w-full bg-gradient-to-r from-purple-600 to-green-600 h-12 text-white"
                    onClick={() => window.open('https://solana.com/grants', '_blank')}
                  >
                    Start Application
                    <ArrowRight className="w-4 h-4 ml-2" />
                  </Button>
                  
                  {/* FIXED: Download function now triggers properly */}
                  <Button 
                    variant="outline" 
                    className="w-full h-12"
                    onClick={handleDownload}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download Estimate (.txt)
                  </Button>
                </div>
              </Card>

              <Card className="p-6 border-2">
                <h3 className="text-lg font-bold mb-4">Estimated Timeline</h3>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Application Review</span>
                    <span className="font-semibold">1-2 weeks</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Audit Duration</span>
                    <span className="font-semibold">
                      {urgency === "standard"
                        ? "4-6 weeks"
                        : urgency === "expedited"
                        ? "2-3 weeks"
                        : "< 2 weeks"}
                    </span>
                  </div>
                  <div className="flex justify-between border-t pt-3">
                    <span className="font-semibold">Total Time</span>
                    <span className="font-bold text-purple-600">
                      {urgency === "standard"
                        ? "5-8 weeks"
                        : urgency === "expedited"
                        ? "3-5 weeks"
                        : "< 4 weeks"}
                    </span>
                  </div>
                </div>
              </Card>

              <Card className="p-6 border-2">
                <h3 className="text-lg font-bold mb-4">Recommended For You</h3>
                <div className="space-y-3">
                  {[
                    { id: 4, name: "Cyfrin", url: "https://cyfrin.io" },
                    { id: 8, name: "Immunefi", url: "https://immunefi.com" },
                    { id: 9, name: "Oak Security", url: "https://oaksecurity.io" }
                  ].map((provider) => (
                    <div 
                      key={provider.id} 
                      onClick={() => window.open(provider.url, '_blank')}
                      className="flex items-center justify-between p-3 bg-gray-50 rounded-lg hover:bg-purple-50 transition-colors cursor-pointer group"
                    >
                      <span className="font-medium group-hover:text-purple-600">{provider.name}</span>
                      <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-purple-600" />
                    </div>
                  ))}
                </div>
              </Card>
            </div>
          </div>
        </div>

        <Card className="mt-12 p-8 bg-gradient-to-r from-blue-50 to-purple-50 border-2">
          <div className="text-center max-w-3xl mx-auto">
            <Info className="w-12 h-12 text-blue-600 mx-auto mb-4" />
            <h3 className="text-2xl font-bold mb-3">How This Estimate Works</h3>
            <p className="text-gray-600 leading-relaxed">
              This calculator provides a rough estimate based on industry standards and typical
              audit pricing. Actual costs may vary based on your project's specific requirements,
              the chosen audit provider, and market conditions. The subsidy amount shown is based
              on the standard 30% coverage provided by the Solana Audit Subsidy Program.
            </p>
          </div>
        </Card>
      </div>
    </div>
  );
}